# Generated by Django 5.2.13 on 2026-04-14 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0001_initial'),
        ('cadastros', '0001_initial'),
        ('contratos', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regra', models.CharField(blank=True, max_length=100, verbose_name='Regra')),
                ('base', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base de cálculo')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual (%)')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('calculada', 'Calculada'), ('aprovada', 'Aprovada'), ('paga', 'Paga')], default='pendente', max_length=10, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiário')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Comissão Financeira',
                'verbose_name_plural': 'Comissões Financeiras',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('caixa', 'Caixa'), ('cartao', 'Cartão'), ('gateway', 'Gateway')], max_length=10, verbose_name='Tipo')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('gateway', models.CharField(blank=True, max_length=50, verbose_name='Gateway')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo inicial')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conciliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('saldo_extrato', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo do extrato')),
                ('saldo_sistema', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo no sistema')),
                ('divergencia', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Divergência')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('conciliada', 'Conciliada')], default='aberta', max_length=15, verbose_name='Status')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='financeiro.contafinanceira', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Conciliação',
                'verbose_name_plural': 'Conciliações',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='TituloFinanceiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('receber', 'A Receber'), ('pagar', 'A Pagar')], max_length=10, verbose_name='Tipo')),
                ('natureza', models.CharField(blank=True, max_length=100, verbose_name='Natureza')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor pago')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('parcial', 'Parcialmente pago'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='aberto', max_length=10, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('cheque', 'Cheque')], max_length=15, verbose_name='Forma de pagamento')),
                ('link_pagamento', models.URLField(blank=True, verbose_name='Link de pagamento')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, verbose_name='Código de barras')),
                ('chave_pix', models.CharField(blank=True, max_length=100, verbose_name='Chave PIX')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='cadastros.centrocusto', verbose_name='Centro de custo')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='financeiro.contafinanceira', verbose_name='Conta')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_financeiros', to='contratos.contrato', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.filial', verbose_name='Filial')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_financeiros', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Título Financeiro',
                'verbose_name_plural': 'Títulos Financeiros',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data da baixa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, verbose_name='Forma de pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/', verbose_name='Comprovante')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_financeiras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas', to='financeiro.contafinanceira', verbose_name='Conta')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='financeiro.titulofinanceiro', verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Baixa',
                'verbose_name_plural': 'Baixas',
                'ordering': ['-data_baixa'],
            },
        ),
    ]
