# Generated by Django 5.2.13 on 2026-04-14 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0001_initial'),
        ('assistencia', '0002_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tipo', models.CharField(choices=[('nfe', 'NF-e'), ('nfse', 'NFS-e'), ('nfce', 'NFC-e'), ('cte', 'CT-e'), ('mdfe', 'MDF-e')], max_length=5, verbose_name='Tipo')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('serie', models.CharField(max_length=5, verbose_name='Série')),
                ('chave', models.CharField(blank=True, max_length=44, verbose_name='Chave de acesso')),
                ('status', models.CharField(choices=[('em_preparacao', 'Em preparação'), ('em_transmissao', 'Em transmissão'), ('autorizado', 'Autorizado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('inutilizado', 'Inutilizado')], default='em_preparacao', max_length=20, verbose_name='Status')),
                ('xml_envio', models.TextField(blank=True, verbose_name='XML de envio')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML de retorno')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='fiscal/docs/', verbose_name='PDF (DANFE)')),
                ('protocolo', models.CharField(blank=True, max_length=30, verbose_name='Protocolo')),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de autorização')),
                ('mensagem_rejeicao', models.TextField(blank=True, verbose_name='Mensagem de rejeição')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('assistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscais', to='assistencia.chamado', verbose_name='Chamado assistência')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.filial', verbose_name='Filial')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscais', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
                'ordering': ['-criado_em'],
                'unique_together': {('empresa', 'tipo', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EventoFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('cancelamento', 'Cancelamento'), ('cce', 'Carta de Correção'), ('inutilizacao', 'Inutilização'), ('contingencia', 'Contingência')], max_length=15, verbose_name='Tipo')),
                ('protocolo', models.CharField(blank=True, max_length=30, verbose_name='Protocolo')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('xml_evento', models.TextField(blank=True, verbose_name='XML do evento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fiscal.documentofiscal', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Evento Fiscal',
                'verbose_name_plural': 'Eventos Fiscais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParametroFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serie_nfe', models.CharField(default='1', max_length=5, verbose_name='Série NF-e')),
                ('serie_nfse', models.CharField(default='1', max_length=5, verbose_name='Série NFS-e')),
                ('serie_nfce', models.CharField(default='1', max_length=5, verbose_name='Série NFC-e')),
                ('ambiente', models.CharField(choices=[('producao', 'Produção'), ('homologacao', 'Homologação')], default='homologacao', max_length=15, verbose_name='Ambiente')),
                ('regime_tributario', models.CharField(max_length=10, verbose_name='Regime tributário')),
                ('certificado_a1', models.FileField(blank=True, null=True, upload_to='fiscal/certs/', verbose_name='Certificado A1')),
                ('certificado_senha', models.CharField(blank=True, max_length=200, verbose_name='Senha do certificado')),
                ('provedor_nfe', models.CharField(blank=True, max_length=100, verbose_name='Provedor NF-e')),
                ('provedor_nfse', models.CharField(blank=True, max_length=100, verbose_name='Provedor NFS-e')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_fiscal', to='administracao.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administracao.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Parâmetro Fiscal',
                'verbose_name_plural': 'Parâmetros Fiscais',
            },
        ),
    ]
