# Generated by Django 5.2.13 on 2026-04-14 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('producao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaocompra',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='producao.ordemproducao', verbose_name='Ordem de Produção'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='pedidos.pedido', verbose_name='Pedido de Origem'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_compra', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='requisicoes',
            field=models.ManyToManyField(blank=True, related_name='cotacoes', to='compras.requisicaocompra', verbose_name='Requisições'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['empresa', 'status'], name='compras_ped_empresa_211be4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['numero'], name='compras_ped_numero_799849_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaocompra',
            index=models.Index(fields=['empresa', 'status'], name='compras_req_empresa_f02771_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaocompra',
            index=models.Index(fields=['empresa', 'prioridade'], name='compras_req_empresa_ae540b_idx'),
        ),
    ]
