# Generated by Django 5.2.13 on 2026-04-14 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('producao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('tipo', models.CharField(choices=[('entrega', 'Entrega'), ('montagem', 'Montagem'), ('vistoria', 'Vistoria'), ('reentrega', 'Reentrega')], max_length=20, verbose_name='Tipo')),
                ('data_prevista', models.DateField(verbose_name='Data prevista')),
                ('janela_inicio', models.TimeField(blank=True, null=True, verbose_name='Janela início')),
                ('janela_fim', models.TimeField(blank=True, null=True, verbose_name='Janela fim')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('status', models.CharField(choices=[('agendando', 'Agendando'), ('confirmado', 'Confirmado'), ('em_rota', 'Em Rota'), ('em_atendimento', 'Em Atendimento'), ('aceite', 'Aceite'), ('pendencia', 'Pendência'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendando', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.filial', verbose_name='Filial')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='pedidos.pedido', verbose_name='Pedido')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('romaneio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='producao.romaneio', verbose_name='Romaneio')),
            ],
            options={
                'verbose_name': 'Agenda de Atendimento',
                'verbose_name_plural': 'Agendas de Atendimento',
                'ordering': ['data_prevista', 'janela_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aceite', models.DateTimeField(verbose_name='Data do aceite')),
                ('assinante_nome', models.CharField(max_length=200, verbose_name='Nome do assinante')),
                ('assinante_doc', models.CharField(blank=True, max_length=30, verbose_name='Documento do assinante')),
                ('foto_assinatura', models.ImageField(blank=True, null=True, upload_to='entrega/aceites/', verbose_name='Foto da assinatura')),
                ('conclusao', models.CharField(choices=[('total', 'Total'), ('parcial', 'Parcial')], max_length=10, verbose_name='Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('nps', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='NPS')),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aceite', to='entrega.agendaatendimento', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Aceite',
                'verbose_name_plural': 'Aceites',
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_verificacao', models.CharField(max_length=255, verbose_name='Item de verificação')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('nok', 'NOK'), ('pendente', 'Pendente')], default='pendente', max_length=10, verbose_name='Status')),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='entrega/checklist/', verbose_name='Evidência')),
                ('observacao', models.CharField(blank=True, max_length=500, verbose_name='Observação')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='entrega.agendaatendimento', verbose_name='Agenda')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_instalacao', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Checklist de Instalação',
                'verbose_name_plural': 'Checklists de Instalação',
            },
        ),
        migrations.CreateModel(
            name='EquipeCampo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('veiculo', models.CharField(blank=True, max_length=100, verbose_name='Veículo')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.filial', verbose_name='Filial')),
                ('membros', models.ManyToManyField(blank=True, related_name='equipes_campo', to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Equipe de Campo',
                'verbose_name_plural': 'Equipes de Campo',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='agendaatendimento',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='entrega.equipecampo', verbose_name='Equipe'),
        ),
        migrations.CreateModel(
            name='OcorrenciaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dano', 'Dano'), ('atraso', 'Atraso'), ('acesso_negado', 'Acesso negado'), ('peca_faltante', 'Peça faltante'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('impacto', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=20, verbose_name='Impacto')),
                ('encaminhamento', models.TextField(blank=True, verbose_name='Encaminhamento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='entrega/ocorrencias/', verbose_name='Foto')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='entrega.agendaatendimento', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Ocorrência de Campo',
                'verbose_name_plural': 'Ocorrências de Campo',
            },
        ),
    ]
