# Generated by Django 5.2.13 on 2026-04-14 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncerramentoChamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('causa_raiz', models.TextField(verbose_name='Causa raiz')),
                ('solucao', models.TextField(verbose_name='Solução')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo total')),
                ('cobrado', models.BooleanField(default=False, verbose_name='Cobrado')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor cobrado')),
                ('nps', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='NPS')),
                ('aceite_cliente', models.BooleanField(default=False, verbose_name='Aceite do cliente')),
            ],
            options={
                'verbose_name': 'Encerramento de Chamado',
                'verbose_name_plural': 'Encerramentos de Chamados',
            },
        ),
        migrations.CreateModel(
            name='PecaReposicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Quantidade')),
                ('origem', models.CharField(choices=[('estoque', 'Estoque'), ('compra', 'Compra'), ('fabricacao', 'Fabricação')], max_length=15, verbose_name='Origem')),
                ('prazo_estimado', models.DateField(blank=True, null=True, verbose_name='Prazo estimado')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
            ],
            options={
                'verbose_name': 'Peça de Reposição',
                'verbose_name_plural': 'Peças de Reposição',
            },
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_prevista', models.DateField(verbose_name='Data prevista')),
                ('data_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Data realizada')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('evidencias', models.JSONField(default=list, help_text='URLs das fotos', verbose_name='Evidências')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('reagendada', 'Reagendada'), ('cancelada', 'Cancelada')], default='agendada', max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Visita Técnica',
                'verbose_name_plural': 'Visitas Técnicas',
                'ordering': ['data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('ambiente', models.CharField(blank=True, max_length=100, verbose_name='Ambiente')),
                ('tipo', models.CharField(choices=[('garantia', 'Garantia'), ('avulso', 'Avulso'), ('manutencao', 'Manutenção')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('triado', 'Triado'), ('agendado', 'Agendado'), ('em_atendimento', 'Em Atendimento'), ('aguardando_peca', 'Aguardando Peça'), ('encerrado', 'Encerrado')], default='aberto', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('sla_horas', models.PositiveIntegerField(default=48, verbose_name='SLA (horas)')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('data_limite_sla', models.DateTimeField(blank=True, null=True, verbose_name='Data limite SLA')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('cobertura_garantia', models.BooleanField(default=True, verbose_name='Cobertura de garantia')),
                ('origem', models.CharField(choices=[('portal', 'Portal'), ('interno', 'Interno'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail')], default='interno', max_length=20, verbose_name='Origem')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='cadastros.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
