# Generated by Django 5.2.13 on 2026-04-14 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0001_initial'),
        ('assistencia', '0001_initial'),
        ('cadastros', '0001_initial'),
        ('contratos', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='contratos.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administracao.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_assistencia', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='encerramentochamado',
            name='chamado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encerramento', to='assistencia.chamado', verbose_name='Chamado'),
        ),
        migrations.AddField(
            model_name='pecareposicao',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='assistencia.chamado', verbose_name='Chamado'),
        ),
        migrations.AddField(
            model_name='pecareposicao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas_reposicao', to='cadastros.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='assistencia.chamado', verbose_name='Chamado'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_tecnicas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
    ]
