# Generated by Django 5.2.13 on 2026-04-14 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackNPS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Nota NPS')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('etapa', models.CharField(blank=True, help_text='Ex: entrega, montagem', max_length=100, verbose_name='Etapa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_nps', to='contratos.contrato', verbose_name='Contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Feedback NPS',
                'verbose_name_plural': 'Feedbacks NPS',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('interno', 'Interno')], max_length=10, verbose_name='Origem')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de leitura')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_portal', to='contratos.contrato', verbose_name='Contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='administracao.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Mensagem do Portal',
                'verbose_name_plural': 'Mensagens do Portal',
                'ordering': ['-criado_em'],
            },
        ),
    ]
